### ISSUE TITLE
Hi, is it secure to use crypto random bytes to generate both access token and refresh token for custom authentication?

### ISSUE THREAD

**Issue by KaizenTamashi** [crypto-utils/random-bytes#2]
## Question
Hi, is it secure to use crypto random bytes to generate both access token and refresh token for custom authentication?

**Comment by dougwilson** [comment]
Hello, this module is simply provided to generate strong pseudo-random bytes. It is a wrapper around the Node.js core `crypto.randomBytes` API.

If you have questions about this module specifically, I can certainly help, but your question above is more generic about just using random bytes for something I don't know the details of in order to adequately answer. I would suggest asking on Stackoverflow.com
